.TH "HOSTMUX" "1" "February 8, 2016" "Linux 4.4.1-2-ARCH" "General Commands Manual"
.nh
.if n .ad l
.SH "NAME"
\fBhostmux\fR
\- Connects to a list of hosts via ssh in separate tmux split panes
.SH "SYNOPSIS"
.HP 8n
\fBhostmux\fR
[\fB\-s\fR\ \fIsession-name\fR]
[\fB\-l\fR\ \fItmux-layout\fR]
[\fB\-r\fR\ \fIremote-host\fR]
[\fB\-x\fR]
[\fB\-h\fR]
[\fIhost_a\fR]
[\fIhost_b\fR]
[\fIhost_n\fR]
.SH "DESCRIPTION"
Call hostmux followed by a list of hosts you want to connect to via ssh.
The script will create a new tmux session with a split pane for each
specified host and connect to it.
.PP
You can then use the synchronize-panes feature of tmux to
multiplex/broadcast commands to all split panes / servers
.PP
Its arguments are as follows:
.TP 8n
\fB\-s\fR
Specify a name for the tmux session. It defaults to
\(oqhostmux\(cq
which means that you can have only one hostmux session at a time if you don't
specify unique names for your sessions
.TP 8n
\fB\-l\fR
Specify a valid tmux layout e.g. even-horizontal, tiled, etc. It defaults
to
\(oqeven-vertical\(cq
.TP 8n
\fB\-r\fR
Specify a remote host used to jump to the hosts in a secured environment.
.TP 8n
\fB\-x\fR
Close the pane and/or session automatically when the ssh session
session exits successfully
.TP 8n
\fB\-h\fR
Display usage information
.TP 8n
\fIhost\fR
Specify a space separated list of one or more user@hostname ssh targets. This
is what you would pass to the ssh command when you are connecting
to a host. Currently there is no support for passing additional flags
to ssh. If you do need them, add them to your ~/.ssh/config
.SH "SEE ALSO"
.TP 8n
tmux(1)
.br
.TP 8n
\fBhttps://github.com/hukl/hostmux\fR
.SH "EXIT STATUS"
.br
The \fBhostmux\fR utility exits\~0 on success, and\~>0 if an error occurs.
.SH "AUTHORS"
\fBhostmux\fR
was written by
John-Paul Bader (hukl),
\fIcontact@smyck.org\fR.
