#!/bin/sh

# Keybinding suggestions for .tmux.conf:
# bind-key a set-window-option synchronize-panes
# bind-key X kill-session


USAGE="hostmux [-h] [-l <tmux layout>] [-s <session name>] HOST A [, HOST B, HOST N]"

# Default Settings
SESSION_NAME=hostmux
LAYOUT=even-vertical

# Get optional user settings
while getopts :l:h opt
do
case $opt in
h)     echo $USAGE
       exit 1
       ;;
l)     LAYOUT=$OPTARG
       ;;
s)     SESSION_NAME=$OPTARG
       ;;
'?')   echo "$0: invalid option -$OPTARG" >&2
       echo $USAGE >&2
       exit 1
       ;;
esac done
shift $((OPTIND - 1))

echo $#
echo $LAYOUT

# The actual script
NUMBER_OF_HOSTS=$#

# Initialize Session
tmux -2 new-session -d -s $SESSION_NAME


# Split as many times as we have hosts as arguments and reset
# the layout each time for even distribution
LOOP_INDEX=1

while [ $LOOP_INDEX -lt $NUMBER_OF_HOSTS ]
do
  tmux split-window -h -d
  tmux select-layout $LAYOUT

  LOOP_INDEX=$(($LOOP_INDEX+1))
done


# Loop through the panes and take the first argument as a ssh host
# then shift the argument list left, increase the index and go
# into next iteration. Now $1 refers to the next argument passed
# to the script
PANE_INDEX=0
PANE_MAX=$(($NUMBER_OF_HOSTS-1))

while [ $PANE_INDEX -le $PANE_MAX ]
do
  tmux send-keys -t $PANE_INDEX "ssh $1" C-m

  shift
  PANE_INDEX=$(($PANE_INDEX+1))
done


# Attach to the session
tmux -2 attach-session -t $SESSION_NAME
